'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Journal6.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Brush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DiagonalLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiagonalLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diagonalRepeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diagonalRepeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimBrickRepeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimBrickRepeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimBrush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimBrush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimDiagonalLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimDiagonalLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimDiagonalRepeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimDiagonalRepeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimDropper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimDropper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimFill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimFill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimFilledCircle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimFilledCircle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimFilledSquare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimFilledSquare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimFilledText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimFilledText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimFlip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimFlip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimGridRepeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimGridRepeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimGuideLines() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimGuideLines", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimHalfdrop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimHalfdrop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimHorizontalLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimHorizontalLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimLasso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimLasso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimMirror() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimMirror", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimRedo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimRedo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimRotateLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimRotateLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimRotateRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimRotateRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimSolidText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimSolidText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimSquare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimSquare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimUndo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimUndo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DimVerticalLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DimVerticalLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dropper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dropper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dropper1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dropper1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilledCircle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilledCircle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilledSquare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilledSquare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FilledText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilledText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property halfdrop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("halfdrop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HorizontalLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HorizontalLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lasso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lasso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mirror() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mirror", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OutlineText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlineText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paintChooser() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("paintChooser", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property PAL1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PAL1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RotateLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RotateLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RotateRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RotateRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SketchCover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SketchCover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SketchCover1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SketchCover1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SketchCover2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SketchCover2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SolidText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SolidText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sprial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sprial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sprial1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sprial1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property square() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("square", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VerticalLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VerticalLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
